### ISSUE TITLE
'Fixed' Menu Bar Home Page

### ISSUE THREAD

**Issue by radiantdeer** [KP-Kepra/WebEdufair15#2]
Menu bar yang nempel diatas kalo window browsernya dikecilin nggak ikut ngescroll, jadi beberapa tulisannya kepotong gitu.
![issue1](https://cloud.githubusercontent.com/assets/11991877/8472657/4b149338-20cd-11e5-8d7b-aebf1906b898.png)
![issue12](https://cloud.githubusercontent.com/assets/11991877/8472658/4b14ce5c-20cd-11e5-96b6-7a07669541f0.png)

**Comment by KP-Kepra** [comment]
Ton, udah gw update ya fixnya, coba dicek.

**Comment by kpkepra** [comment]
Ton, udah gw update ya fixnya, coba dicek. @antoniosetya 
Navbarnya gw bikin menyusut pas dizoom, sama ada minimum width.
Masih cari cara utk scroll ke samping kanan kalau bener" dizoom

*Sori spam Timeline, tiba-tiba ini issue keclose sendiri ._.
